try:
    int('a')
except ValueError as e:
    print e.message
    raise e 
except Exception:
    
else:
    print "it is ok"
